export {default as InputColor} from './InputColor.vue'
export {default as InputDropdown} from './InputDropdown.vue'
export {default as InputNumber} from './InputNumber.vue'
export {default as InputString} from './InputString.vue'
export {default as InputRect2d} from './InputRect2d.vue'
export {default as InputRotery} from './InputRotery.vue'
export {default as InputMat2d} from './InputMat2d.vue'
export {default as InputSeed} from './InputSeed.vue'
