export {default as InputColor} from './InputColor.vue'
export {default as InputDropdown} from './InputDropdown.vue'
export {default as InputNumber} from './InputNumber.vue'
export {default as InputString} from './InputString.vue'
export {default as InputRotery} from './InputRotery.vue'
export {default as InputSeed} from './InputSeed.vue'
export {default as InputTranslate} from './InputTranslate.vue'
