<template>
	<div class="MonacoEditor" ref="rootEl" />
</template>

<script lang="ts">
import './languages/glisp'
import './languages/glsl'

import {templateRef} from '@vueuse/core'
import * as Monaco from 'monaco-editor'
import {
	defineComponent,
	inject,
	onMounted,
	onUnmounted,
	Ref,
	ref,
	watch,
} from 'vue'

export default defineComponent({
	name: 'MonacoEditor',
	props: {
		modelValue: {
			type: String,
			required: true,
		},
		lang: {
			type: String,
			default: 'glisp',
		},
	},
	emits: ['update:modelValue'],
	setup(props, context) {
		const rootEl = templateRef('rootEl')

		let editor: ReturnType<typeof Monaco.editor.create>

		const scheme = inject<Ref<{[name: string]: string}>>('scheme', ref({}))

		onMounted(() => {
			if (!rootEl.value) return

			editor = Monaco.editor.create(rootEl.value as HTMLElement, {
				value: props.modelValue,
				language: props.lang,
				fontFamily: "'Fira Code'",
				minimap: {enabled: false},
				folding: false,
				lineNumbers: 'off',
				lineHeight: 21,
				fontLigatures: true,
				fontSize: 14,
				renderLineHighlight: 'none',
			})

			watch(
				() => scheme,
				() => {
					if (!editor) return

					const {
						base00,
						base01,
						base02,
						base03,
						base04,
						base05,
						base06,
						base07,
						base08,
						base09,
						base0A,
						base0B,
						base0C,
						base0D,
						base0E,
						base0F,
						accent,
					} = scheme.value

					const frame = base05 + '33'

					Monaco.editor.defineTheme('custom-theme', {
						base: 'vs-dark',
						inherit: true,
						rules: [
							{token: '', foreground: base04},
							{token: 'string', foreground: base0B},
							{token: 'string.escape', foreground: base0C},
							{token: 'comment', foreground: base03},
							{token: 'white', foreground: base03},
							{token: 'number', foreground: base09},
							{token: 'delimiter.slash', foreground: base0A},
							{token: 'delimiter', foreground: base05},
							{token: 'constant', foreground: base09},
							{token: 'support', foreground: base0C},
							{token: 'identifier', foreground: base08},
							{token: 'function', foreground: base0D},
							{token: 'keyword', foreground: base0E},
						],
						colors: {
							'editorBracketMatch.background': base02,
							'editorBracketMatch.border': base03,
							foreground: base05,
							'selection.background': base09,
							descriptionForeground: base03,
							errorForeground: base0B,
							'icon.foreground': base04,
							'textBlockQuote.background': base01,
							'textBlockQuote.border': base09,
							'textCodeBlock.background': base01,
							'textLink.activeForeground': base08,
							'textLink.foreground': base09,
							'textPreformat.foreground': base09,
							'button.background': base01,
							'button.foreground': base07,
							'button.hoverBackground': base04,
							'button.secondaryForeground': base07,
							'button.secondaryBackground': base0F,
							'button.secondaryHoverBackground': base04,
							'checkbox.background': base01,
							'checkbox.foreground': base05,
							'dropdown.background': base01,
							'dropdown.listBackground': base01,
							'dropdown.foreground': base05,
							'input.background': base01,
							'input.border': base01,
							'input.foreground': base05,
							'input.placeholderForeground': base03,
							'inputOption.activeBackground': base02,
							'inputOption.activeBorder': accent,
							'inputOption.activeForeground': base05,
							'inputValidation.errorBackground': base0B,
							'inputValidation.errorForeground': base05,
							'inputValidation.errorBorder': base0B,
							'inputValidation.infoBackground': base09,
							'inputValidation.infoForeground': base05,
							'inputValidation.infoBorder': base09,
							'inputValidation.warningBackground': base0D,
							'inputValidation.warningForeground': base05,
							'inputValidation.warningBorder': base0D,
							'scrollbar.shadow': '#00000000',
							'scrollbarSlider.activeBackground': base02 + '6f',
							'scrollbarSlider.background': '#ff0000',
							'scrollbarSlider.hoverBackground': '#f0f',
							'badge.background': base00,
							'badge.foreground': base05,
							'activityBar.background': '#00000000',
							'activityBar.dropBackground': base07,
							'activityBar.foreground': base05,
							'activityBar.inactiveForeground': base03,
							'activityBarBadge.background': base09,
							'activityBarBadge.foreground': base07,
							'activityBar.activeBackground': base02,
							'minimapGutter.addedBackground': base0E,
							'minimapGutter.modifiedBackground': base0F,
							'minimapGutter.deletedBackground': base0B,
							'editorGroup.background': '#00000000',
							'editorGroup.dropBackground': base02 + '6f',
							'editorGroupHeader.noTabsBackground': base01,
							'editorGroupHeader.tabsBackground': base01,
							'editorGroup.emptyBackground': '#00000000',
							'tab.activeBackground': '#00000000',
							'tab.unfocusedActiveBackground': '#00000000',
							'tab.activeForeground': base05,
							'tab.inactiveBackground': base01,
							'tab.inactiveForeground': base03,
							'tab.unfocusedActiveForeground': base04,
							'tab.unfocusedInactiveForeground': base03,
							'tab.hoverBackground': base02,
							'tab.unfocusedHoverBackground': base02,
							'tab.activeModifiedBorder': base09,
							'tab.inactiveModifiedBorder': base09,
							'tab.unfocusedActiveModifiedBorder': base09,
							'tab.unfocusedInactiveModifiedBorder': base09,
							'editorPane.background': '#00000000',
							'editor.background': '#00000000',
							'editor.foreground': base05,
							'editorCursor.foreground': base05,
							'editor.selectionBackground': base01,
							'editor.inactiveSelectionBackground': base01,
							'editor.selectionHighlightBackground': base01,
							'editor.wordHighlightBackground': base02 + '6f',
							'editor.wordHighlightStrongBackground': base03 + '6f',
							'editor.findMatchBackground': base0D + '6f',
							'editor.findMatchHighlightBackground': base0C + '6f',
							'editor.findRangeHighlightBackground': base01 + '6f',
							'editor.hoverHighlightBackground': base02 + '6f',
							'editor.lineHighlightBackground': base01,
							'editorLink.activeForeground': base09,
							'editor.rangeHighlightBackground': base01 + '6f',
							'editorWhitespace.foreground': base01,
							'editorIndentGuide.background': base01,
							'editorIndentGuide.activeBackground': base02,
							'editorRuler.foreground': base03,
							'editorCodeLens.foreground': base02,
							'editorLightBulb.foreground': base0D,
							'editorLightBulbAutoFix.foreground': base09,
							'editorOverviewRuler.findMatchForeground': base0D + '6f',
							'editorOverviewRuler.rangeHighlightForeground': base03 + '6f',
							'editorOverviewRuler.selectionHighlightForeground': base02 + '6f',
							'editorOverviewRuler.wordHighlightForeground': base07 + '6f',
							'editorOverviewRuler.wordHighlightStrongForeground':
								base09 + '6f',
							'editorOverviewRuler.errorForeground': base0B,
							'editorOverviewRuler.warningForeground': base0D,
							'editorOverviewRuler.infoForeground': base08,
							'editorOverviewRuler.bracketMatchForeground': base06,
							'editorOverviewRuler.border': base01,
							'editorError.foreground': base0B,
							'editorWarning.foreground': base0D,
							'editorInfo.foreground': base08,
							'editorHint.foreground': base09,
							'problemsErrorIcon.foreground': base0B,
							'problemsWarningIcon.foreground': base0D,
							'problemsInfoIcon.foreground': base08,
							'editorGutter.background': '#00000000',
							'editorGutter.commentRangeForeground': base04,
							'editorGutter.foldingControlForeground': base05,
							'editorWidget.foreground': base05,
							'editorWidget.background': base00,
							'editorWidget.border': accent,
							'editorSuggestWidget.background': base00,
							'editorSuggestWidget.border': base05 + '33',
							'editorSuggestWidget.foreground': base04,
							'editorSuggestWidget.highlightForeground': accent,
							'editorSuggestWidget.selectedBackground': base01,
							'editorHoverWidget.foreground': base05,
							'editorHoverWidget.background': '#00000000',
							'keybindingLabel.background': '#ff000000',
							'keybindingLabel.foreground': base00,
							'keybindingLabel.border': base04,
							'keybindingLabel.bottomBorder': base04,
							'debugExceptionWidget.background': base01,
							'editorMarkerNavigation.background': base01,
							'editorMarkerNavigationError.background': base0B,
							'editorMarkerNavigationWarning.background': base0D,
							'editorMarkerNavigationInfo.background': base09,
							'peekViewEditor.background': base01,
							'peekViewEditorGutter.background': base01,
							'peekViewEditor.matchHighlightBackground': base0C + '6f',
							'peekViewResult.background': '#00000000',
							'peekViewResult.fileForeground': base05,
							'peekViewResult.lineForeground': base03,
							'peekViewResult.matchHighlightBackground': base0C + '6f',
							'peekViewResult.selectionBackground': base01,
							'peekViewResult.selectionForeground': base05,
							'peekViewTitle.background': base02,
							'peekViewTitleDescription.foreground': base03,
							'peekViewTitleLabel.foreground': base05,
							'merge.currentContentBackground': base09 + '40',
							'merge.currentHeaderBackground': base09 + '40',
							'merge.incomingContentBackground': base0E + '60',
							'merge.incomingHeaderBackground': base0E + '60',
							'editorOverviewRuler.currentContentForeground': base09,
							'editorOverviewRuler.incomingContentForeground': base0E,
							'editorOverviewRuler.commonContentForeground': base0A,
							'panel.background': '#00000000',
							'panel.dropBackground': base01 + '6f',
							'panelTitle.activeForeground': base05,
							'panelTitle.inactiveForeground': base03,
							'menubar.background': base00,
							'menubar.selectionForeground': base00,
							'menubar.selectionBackground': accent,
							'menubar.selectionBorder': '#00000000',
							'menu.selectionBorder': '#00000000',
							'menu.border': frame,
							'menu.foreground': base04,
							'menu.background': base00,
							'menu.selectionForeground': base00,
							'menu.selectionBackground': accent,
							'menu.separatorBackground': base02,
							'pickerGroup.foreground': base03,
							'quickInput.background': base01,
							'quickInput.foreground': base05,
							'settings.headerForeground': base05,
							'settings.modifiedItemIndicator': base09,
							'settings.modifiedItemForeground': base09,
							'settings.dropdownBackground': base01,
							'settings.dropdownForeground': base05,
							'settings.checkboxBackground': base01,
							'settings.checkboxForeground': base05,
							'settings.textInputBackground': base01,
							'settings.textInputForeground': base05,
							'settings.numberInputBackground': base01,
							'settings.numberInputForeground': base05,
							'settings.focusedRowBackground': base02,
							'symbolIcon.arrayForeground': base05,
							'symbolIcon.booleanForeground': base0C,
							'symbolIcon.classForeground': base0D,
							'symbolIcon.constantForeground': base0C,
							'symbolIcon.constructorForeground': base09,
							'symbolIcon.enumeratorForeground': base0C,
							'symbolIcon.enumeratorMemberForeground': base09,
							'symbolIcon.eventForeground': base0D,
							'symbolIcon.fieldForeground': base0B,
							'symbolIcon.fileForeground': base05,
							'symbolIcon.folderForeground': base05,
							'symbolIcon.functionForeground': base09,
							'symbolIcon.interfaceForeground': base09,
							'symbolIcon.keywordForeground': base0F,
							'symbolIcon.methodForeground': base09,
							'symbolIcon.moduleForeground': base05,
							'symbolIcon.namespaceForeground': base05,
							'symbolIcon.nullForeground': base0A,
							'symbolIcon.numberForeground': base0C,
							'symbolIcon.propertyForeground': base05,
							'symbolIcon.snippetForeground': base05,
							'symbolIcon.stringForeground': base0E,
							'symbolIcon.structForeground': base0D,
							'symbolIcon.textForeground': base05,
							'symbolIcon.variableForeground': base0B,
							'notebook.rowHoverBackground': base01,
							'widget.shadow': base00,
							'activityBar.background': '#1d2027',
							'activityBar.border': '#1d2027',
							'activityBar.foreground': '#a7adba',
							'activityBarBadge.background': '#518cc7',
							'activityBarBadge.foreground': '#dfe1e8',
							'badge.background': '#518cc7',
							'badge.foreground': '#dfe1e8',
							'button.background': '#5989b9',
							'button.foreground': '#eff1f5',
							'button.hoverBackground': '#6498cc',
							'debugExceptionWidget.background': '#323b4f',
							'debugExceptionWidget.border': '#bf616a',
							'debugToolBar.background': '#323843',
							'diffEditor.insertedTextBackground': '#a3be8c20',
							'diffEditor.insertedTextBorder': '#a3be8c18',
							'diffEditor.removedTextBackground': '#bf616a20',
							'diffEditor.removedTextBorder': '#bf616a18',
							'dropdown.background': '#343d46',
							'dropdown.border': '#343d46',
							'dropdown.foreground': '#a7adba',
							'editor.background': '#2b303b',
							'editor.findMatchBackground': '#d0877033',
							'editor.findMatchHighlightBackground': '#d0877033',
							'editor.findRangeHighlightBackground': '#5989b933',
							'editor.foreground': '#c0c5ce',
							'editor.hoverHighlightBackground': '#2f4f6c4f',
							'editor.lineHighlightBackground': '#323843',
							'editor.lineHighlightBorder': '#323843',
							'editor.rangeHighlightBackground': '#5989b933',
							'editor.selectionBackground': '#5989b96f',
							'editor.selectionHighlightBackground': '#5989b92f',
							'editor.wordHighlightBackground': '#2f4f6c',
							'editor.wordHighlightStrongBackground': '#2f4f6c',
							'editorBracketMatch.background': '#4f5b66',
							'editorBracketMatch.border': '#a7adba',
							'editorCursor.foreground': '#c0c5ce',
							'editorError.foreground': '#9b4d55',
							'editorGroup.border': '#1a1d23',
							'editorGroup.dropBackground': '#343d466f',
							'editorGroupHeader.noTabsBackground': '#282d37',
							'editorGroupHeader.tabsBackground': '#21252d',
							'editorGutter.addedBackground': '#a3be8c',
							'editorGutter.deletedBackground': '#bf616a',
							'editorGutter.modifiedBackground': '#518cc7',
							'editorHoverWidget.background': '#252932',
							'editorHoverWidget.border': '#1a1d23',
							'editorIndentGuide.background': '#343d46',
							'editorInfo.foreground': '#518cc7',
							'editorLineNumber.foreground': '#47525c',
							'editorLink.activeForeground': '#5989b9',
							'editorMarkerNavigation.background': '#323b4f',
							'editorMarkerNavigationError.background': '#9b4d55',
							'editorMarkerNavigationWarning.background': '#ebcb8b',
							'editorOverviewRuler.addedForeground': '#a3be8c',
							'editorOverviewRuler.border': '#343d46',
							'editorOverviewRuler.deletedForeground': '#bf616a',
							'editorOverviewRuler.errorForeground': '#a93642',
							'editorOverviewRuler.findMatchForeground': '#96b5b4',
							'editorOverviewRuler.infoForeground': '#518cc7',
							'editorOverviewRuler.modifiedForeground': '#518cc7',
							'editorOverviewRuler.warningForeground': '#ebcb8b',
							'editorOverviewRuler.wordHighlightForeground': '#b48ead',
							'editorSuggestWidget.background': '#252932',
							'editorSuggestWidget.border': '#1a1d23',
							'editorSuggestWidget.foreground': '#8fa1b3',
							'editorSuggestWidget.highlightForeground': '#5c6bc0',
							'editorSuggestWidget.selectedBackground': '#343d46',
							'editorWarning.foreground': '#ebcb8b',
							'editorWhitespace.foreground': '#4f5b66',
							'editorWidget.background': '#323843',
							'editorWidget.border': '#518cc7',
							errorForeground: '#c0c5cf',
							'extensionButton.prominentBackground': '#78975e',
							'extensionButton.prominentForeground': '#eff1f5',
							'extensionButton.prominentHoverBackground': '#88a470',
							focusBorder: '#518cc7',
							foreground: '#a7adba',
							'gitDecoration.conflictingResourceForeground': '#88363f',
							'gitDecoration.deletedResourceForeground': '#d08770',
							'gitDecoration.ignoredResourceForeground': '#65737e',
							'gitDecoration.modifiedResourceForeground': '#ebcb8bda',
							'gitDecoration.submoduleResourceForeground': '#518cc7',
							'gitDecoration.untrackedResourceForeground': '#a3be8c',
							'input.background': '#252932',
							'input.border': '#323843',
							'input.foreground': '#a7adba',
							'inputOption.activeBorder': '#d08770',
							'inputValidation.errorBackground': '#9b4d55',
							'inputValidation.errorBorder': '#9b4d55',
							'inputValidation.infoBackground': '#5989b9',
							'inputValidation.infoBorder': '#5989b9',
							'inputValidation.warningBackground': '#ebcb8b',
							'inputValidation.warningBorder': '#ebcb8b',
							'list.activeSelectionBackground': '#343d46',
							'list.activeSelectionForeground': '#eff1f5',
							'list.dropBackground': '#2b303b',
							'list.errorForeground': '#9b4d55',
							'list.focusBackground': '#343d46',
							'list.highlightForeground': '#518cc7',
							'list.hoverBackground': '#292d38',
							'list.inactiveSelectionBackground': '#2b303b',
							'notificationCenter.border': '#252932',
							'notificationCenterHeader.background': '#2f4f6c',
							'notificationCenterHeader.foreground': '#dfe1e8',
							'notificationLink.foreground': '#2f4f6c',
							'notificationToast.border': '#2f4f6c',
							'panel.background': '#252932',
							'panel.border': '#1a1d23',
							'panelTitle.activeBorder': '#518cc7',
							'panelTitle.activeForeground': '#c0c5ce',
							'panelTitle.inactiveForeground': '#6e7d88',
							'peekView.border': '#518cc7',
							'peekViewEditor.background': '#323b4f',
							'peekViewEditor.matchHighlightBackground': '#454e61',
							'peekViewResult.background': '#21252d',
							'peekViewResult.fileForeground': '#518cc7',
							'peekViewResult.lineForeground': '#8fa1b3',
							'peekViewResult.matchHighlightBackground': '#343d46',
							'peekViewResult.selectionBackground': '#343d46',
							'peekViewResult.selectionForeground': '#eff1f5',
							'peekViewTitle.background': '#518cc7',
							'peekViewTitleDescription.foreground': '#eff1f597',
							'peekViewTitleLabel.foreground': '#eff1f5',
							'pickerGroup.border': '#4f5b66',
							'pickerGroup.foreground': '#518cc7',
							'progressBar.background': '#5c6bc0',
							'scrollbar.shadow': '#1a1d237f',
							'scrollbarSlider.activeBackground': '#5c69769f',
							'scrollbarSlider.background': '#4f5b667f',
							'scrollbarSlider.hoverBackground': '#5c69767f',
							'sideBar.background': '#21252d',
							'sideBarSectionHeader.background': '#2f373f',
							'sideBarTitle.foreground': '#a7adba',
							'statusBar.background': '#1d2027',
							'statusBar.debuggingBackground': '#923a1b',
							'statusBar.debuggingForeground': '#dfe1e8',
							'statusBar.foreground': '#a7adba',
							'statusBar.noFolderBackground': '#5d2b54',
							'statusBarItem.activeBackground': '#518cc755',
							'statusBarItem.hoverBackground': '#518cc744',
							'tab.activeBackground': '#2b303b',
							'tab.activeForeground': '#dfe1e8',
							'tab.border': '#21252d',
							'tab.hoverBackground': '#343d46',
							'tab.inactiveBackground': '#21252d',
							'tab.inactiveForeground': '#6e7d88',
							'tab.unfocusedHoverBackground': '#323843',
							'terminal.ansiBlack': '#252932',
							'terminal.ansiBlue': '#61afef',
							'terminal.ansiBrightBlack': '#545862',
							'terminal.ansiBrightBlue': '#61afef',
							'terminal.ansiBrightCyan': '#56b6c2',
							'terminal.ansiBrightGreen': '#98c379',
							'terminal.ansiBrightMagenta': '#c678dd',
							'terminal.ansiBrightRed': '#e06c75',
							'terminal.ansiBrightWhite': '#c8ccd4',
							'terminal.ansiBrightYellow': '#e5c07b',
							'terminal.ansiCyan': '#56b6c2',
							'terminal.ansiGreen': '#98c379',
							'terminal.ansiMagenta': '#c678dd',
							'terminal.ansiRed': '#e06c75',
							'terminal.ansiWhite': '#abb2bf',
							'terminal.ansiYellow': '#e5c07b',
							'terminal.background': '#252932',
							'terminal.foreground': '#abb2bf',
							'terminalCursor.background': '#252932',
							'terminalCursor.foreground': '#e06c75',
							'textLink.foreground': '#5c6bc0',
							'titleBar.activeBackground': '#1d2027',
							'titleBar.inactiveBackground': '#1d2027',
							'widget.shadow': '#252932',
							'activityBar.activeBorder': '#a7adba',
							'activityBar.dropBorder': '#a7adba',
							'activityBar.inactiveForeground': '#a7adba66',
							'banner.background': '#343d46',
							'banner.foreground': '#eff1f5',
							'banner.iconForeground': '#518cc7',
							'breadcrumb.activeSelectionForeground': '#bbbfc9',
							'breadcrumb.background': '#2b303b',
							'breadcrumb.focusForeground': '#bbbfc9',
							'breadcrumb.foreground': '#a7adbacc',
							'breadcrumbPicker.background': '#323843',
							'button.secondaryBackground': '#3a3d41',
							'button.secondaryForeground': '#ffffff',
							'button.secondaryHoverBackground': '#45494e',
							'charts.blue': '#518cc7',
							'charts.foreground': '#a7adba',
							'charts.green': '#89d185',
							'charts.lines': '#a7adba80',
							'charts.orange': '#d18616',
							'charts.purple': '#b180d7',
							'charts.red': '#9b4d55',
							'charts.yellow': '#ebcb8b',
							'checkbox.background': '#343d46',
							'checkbox.border': '#343d46',
							'checkbox.foreground': '#a7adba',
							'debugConsole.errorForeground': '#c0c5cf',
							'debugConsole.infoForeground': '#518cc7',
							'debugConsole.sourceForeground': '#a7adba',
							'debugConsole.warningForeground': '#ebcb8b',
							'debugConsoleInputIcon.foreground': '#a7adba',
							'debugIcon.breakpointCurrentStackframeForeground': '#ffcc00',
							'debugIcon.breakpointDisabledForeground': '#848484',
							'debugIcon.breakpointForeground': '#e51400',
							'debugIcon.breakpointStackframeForeground': '#89d185',
							'debugIcon.breakpointUnverifiedForeground': '#848484',
							'debugIcon.continueForeground': '#75beff',
							'debugIcon.disconnectForeground': '#f48771',
							'debugIcon.pauseForeground': '#75beff',
							'debugIcon.restartForeground': '#89d185',
							'debugIcon.startForeground': '#89d185',
							'debugIcon.stepBackForeground': '#75beff',
							'debugIcon.stepIntoForeground': '#75beff',
							'debugIcon.stepOutForeground': '#75beff',
							'debugIcon.stepOverForeground': '#75beff',
							'debugIcon.stopForeground': '#f48771',
							'debugTokenExpression.boolean': '#4e94ce',
							'debugTokenExpression.error': '#f48771',
							'debugTokenExpression.name': '#c586c0',
							'debugTokenExpression.number': '#b5cea8',
							'debugTokenExpression.string': '#ce9178',
							'debugTokenExpression.value': '#cccccc99',
							'debugView.exceptionLabelBackground': '#6c2022',
							'debugView.exceptionLabelForeground': '#a7adba',
							'debugView.stateLabelBackground': '#88888844',
							'debugView.stateLabelForeground': '#a7adba',
							'debugView.valueChangedHighlight': '#569cd6',
							descriptionForeground: '#a7adbab3',
							'diffEditor.diagonalFill': '#cccccc33',
							'editor.focusedStackFrameHighlightBackground': '#7abd7a4d',
							'editor.foldBackground': '#5989b921',
							'editor.inactiveSelectionBackground': '#5989b938',
							'editor.inlineValuesBackground': '#ffc80033',
							'editor.inlineValuesForeground': '#ffffff80',
							'editor.linkedEditingBackground': '#ff00004d',
							'editor.snippetFinalTabstopHighlightBorder': '#525252',
							'editor.snippetTabstopHighlightBackground': '#7c7c7c4d',
							'editor.stackFrameHighlightBackground': '#ffff0033',
							'editor.symbolHighlightBackground': '#d0877033',
							'editorActiveLineNumber.foreground': '#c6c6c6',
							'editorCodeLens.foreground': '#999999',
							'editorGhostText.foreground': '#ffffff56',
							'editorGutter.background': '#2b303b',
							'editorGutter.commentRangeForeground': '#c5c5c5',
							'editorGutter.foldingControlForeground': '#c5c5c5',
							'editorHint.foreground': '#eeeeeeb3',
							'editorHoverWidget.foreground': '#a7adba',
							'editorHoverWidget.statusBarBackground': '#2c313c',
							'editorIndentGuide.activeBackground': '#4f5b66',
							'editorInlayHint.background': '#a7adba',
							'editorInlayHint.foreground': '#323843',
							'editorLightBulb.foreground': '#ffcc00',
							'editorLightBulbAutoFix.foreground': '#75beff',
							'editorLineNumber.activeForeground': '#c6c6c6',
							'editorMarkerNavigationInfo.background': '#518cc7',
							'editorOverviewRuler.bracketMatchForeground': '#a0a0a0',
							'editorOverviewRuler.commonContentForeground': '#60606066',
							'editorOverviewRuler.currentContentForeground': '#40c8ae80',
							'editorOverviewRuler.incomingContentForeground': '#40a6ff80',
							'editorOverviewRuler.rangeHighlightForeground': '#007acc99',
							'editorOverviewRuler.selectionHighlightForeground': '#a0a0a0cc',
							'editorOverviewRuler.wordHighlightStrongForeground': '#c0a0c0cc',
							'editorPane.background': '#2b303b',
							'editorRuler.foreground': '#5a5a5a',
							'editorSuggestWidget.focusHighlightForeground': '#518cc7',
							'editorSuggestWidget.selectedForeground': '#eff1f5',
							'editorUnnecessaryCode.opacity': '#000000aa',
							'editorWidget.foreground': '#a7adba',
							'extensionBadge.remoteBackground': '#518cc7',
							'extensionBadge.remoteForeground': '#dfe1e8',
							'extensionIcon.starForeground': '#ff8e00',
							'gitDecoration.addedResourceForeground': '#81b88b',
							'gitDecoration.renamedResourceForeground': '#73c991',
							'gitDecoration.stageDeletedResourceForeground': '#c74e39',
							'gitDecoration.stageModifiedResourceForeground': '#e2c08d',
							'icon.foreground': '#c5c5c5',
							'input.placeholderForeground': '#a7adba80',
							'inputOption.activeBackground': '#518cc766',
							'inputOption.activeForeground': '#ffffff',
							'keybindingLabel.background': '#8080802b',
							'keybindingLabel.border': '#33333399',
							'keybindingLabel.bottomBorder': '#44444499',
							'keybindingLabel.foreground': '#cccccc',
							'list.deemphasizedForeground': '#8c8c8c',
							'list.filterMatchBackground': '#d0877033',
							'list.focusHighlightForeground': '#518cc7',
							'list.focusOutline': '#518cc7',
							'list.invalidItemForeground': '#b89500',
							'list.warningForeground': '#cca700',
							'listFilterWidget.background': '#653723',
							'listFilterWidget.noMatchesOutline': '#be1100',
							'listFilterWidget.outline': '#00000000',
							'menu.background': '#343d46',
							'menu.foreground': '#a7adba',
							'menu.selectionBackground': '#343d46',
							'menu.selectionForeground': '#eff1f5',
							'menu.separatorBackground': '#bbbbbb',
							'menubar.selectionBackground': '#ffffff1a',
							'menubar.selectionForeground': '#cccccc',
							'merge.commonContentBackground': '#60606029',
							'merge.commonHeaderBackground': '#60606066',
							'merge.currentContentBackground': '#40c8ae33',
							'merge.currentHeaderBackground': '#40c8ae80',
							'merge.incomingContentBackground': '#40a6ff33',
							'merge.incomingHeaderBackground': '#40a6ff80',
							'minimap.errorHighlight': '#ff1212b3',
							'minimap.findMatchHighlight': '#d18616',
							'minimap.selectionHighlight': '#264f78',
							'minimap.warningHighlight': '#ebcb8b',
							'minimapGutter.addedBackground': '#587c0c',
							'minimapGutter.deletedBackground': '#94151b',
							'minimapGutter.modifiedBackground': '#0c7d9d',
							'minimapSlider.activeBackground': '#5c697650',
							'minimapSlider.background': '#4f5b663f',
							'minimapSlider.hoverBackground': '#5c69763f',
							'notebook.cellBorderColor': '#2b303b',
							'notebook.cellInsertionIndicator': '#518cc7',
							'notebook.cellStatusBarItemHoverBackground': '#ffffff26',
							'notebook.cellToolbarSeparator': '#80808059',
							'notebook.focusedCellBorder': '#518cc7',
							'notebook.focusedEditorBorder': '#518cc7',
							'notebook.focusedRowBorder': '#ffffff1f',
							'notebook.inactiveFocusedCellBorder': '#2b303b',
							'notebook.outputContainerBackgroundColor': '#2b303b',
							'notebook.rowHoverBackground': '#80808012',
							'notebook.selectedCellBackground': '#2b303b',
							'notebook.selectedCellBorder': '#2b303b',
							'notebook.symbolHighlightBackground': '#ffffff0b',
							'notebookScrollbarSlider.activeBackground': '#5c69769f',
							'notebookScrollbarSlider.background': '#4f5b667f',
							'notebookScrollbarSlider.hoverBackground': '#5c69767f',
							'notebookStatusErrorIcon.foreground': '#c0c5cf',
							'notebookStatusRunningIcon.foreground': '#a7adba',
							'notebookStatusSuccessIcon.foreground': '#89d185',
							'notifications.background': '#323843',
							'notifications.border': '#2f4f6c',
							'notifications.foreground': '#a7adba',
							'notificationsErrorIcon.foreground': '#9b4d55',
							'notificationsInfoIcon.foreground': '#518cc7',
							'notificationsWarningIcon.foreground': '#ebcb8b',
							'panel.dropBorder': '#c0c5ce',
							'panelSection.border': '#1a1d23',
							'panelSection.dropBackground': '#343d466f',
							'panelSectionHeader.background': '#80808033',
							'peekViewEditorGutter.background': '#323b4f',
							'ports.iconRunningProcessForeground': '#518cc7',
							'problemsErrorIcon.foreground': '#9b4d55',
							'problemsInfoIcon.foreground': '#518cc7',
							'problemsWarningIcon.foreground': '#ebcb8b',
							'quickInput.background': '#323843',
							'quickInput.foreground': '#a7adba',
							'quickInputList.focusBackground': '#343d46',
							'quickInputList.focusForeground': '#eff1f5',
							'quickInputTitle.background': '#ffffff1b',
							'sash.hoverBorder': '#518cc7',
							'scm.providerBorder': '#454545',
							'searchEditor.findMatchBackground': '#d0877022',
							'searchEditor.textInputBorder': '#323843',
							'settings.checkboxBackground': '#343d46',
							'settings.checkboxBorder': '#343d46',
							'settings.checkboxForeground': '#a7adba',
							'settings.dropdownBackground': '#343d46',
							'settings.dropdownBorder': '#343d46',
							'settings.dropdownForeground': '#a7adba',
							'settings.dropdownListBorder': '#518cc7',
							'settings.focusedRowBackground': '#80808024',
							'settings.headerForeground': '#e7e7e7',
							'settings.modifiedItemIndicator': '#0c7d9d',
							'settings.numberInputBackground': '#252932',
							'settings.numberInputBorder': '#323843',
							'settings.numberInputForeground': '#a7adba',
							'settings.textInputBackground': '#252932',
							'settings.textInputBorder': '#323843',
							'settings.textInputForeground': '#a7adba',
							'sideBar.dropBackground': '#343d466f',
							'statusBar.noFolderForeground': '#a7adba',
							'statusBarItem.errorBackground': '#677288',
							'statusBarItem.errorForeground': '#ffffff',
							'statusBarItem.prominentBackground': '#00000080',
							'statusBarItem.prominentForeground': '#a7adba',
							'statusBarItem.prominentHoverBackground': '#0000004d',
							'statusBarItem.remoteBackground': '#518cc7',
							'statusBarItem.remoteForeground': '#dfe1e8',
							'symbolIcon.arrayForeground': '#a7adba',
							'symbolIcon.booleanForeground': '#a7adba',
							'symbolIcon.classForeground': '#ee9d28',
							'symbolIcon.colorForeground': '#a7adba',
							'symbolIcon.constantForeground': '#a7adba',
							'symbolIcon.constructorForeground': '#b180d7',
							'symbolIcon.enumeratorForeground': '#ee9d28',
							'symbolIcon.enumeratorMemberForeground': '#75beff',
							'symbolIcon.eventForeground': '#ee9d28',
							'symbolIcon.fieldForeground': '#75beff',
							'symbolIcon.fileForeground': '#a7adba',
							'symbolIcon.folderForeground': '#a7adba',
							'symbolIcon.functionForeground': '#b180d7',
							'symbolIcon.interfaceForeground': '#75beff',
							'symbolIcon.keyForeground': '#a7adba',
							'symbolIcon.keywordForeground': '#a7adba',
							'symbolIcon.methodForeground': '#b180d7',
							'symbolIcon.moduleForeground': '#a7adba',
							'symbolIcon.namespaceForeground': '#a7adba',
							'symbolIcon.nullForeground': '#a7adba',
							'symbolIcon.numberForeground': '#a7adba',
							'symbolIcon.objectForeground': '#a7adba',
							'symbolIcon.operatorForeground': '#a7adba',
							'symbolIcon.packageForeground': '#a7adba',
							'symbolIcon.propertyForeground': '#a7adba',
							'symbolIcon.referenceForeground': '#a7adba',
							'symbolIcon.snippetForeground': '#a7adba',
							'symbolIcon.stringForeground': '#a7adba',
							'symbolIcon.structForeground': '#a7adba',
							'symbolIcon.textForeground': '#a7adba',
							'symbolIcon.typeParameterForeground': '#a7adba',
							'symbolIcon.unitForeground': '#a7adba',
							'symbolIcon.variableForeground': '#75beff',
							'tab.activeModifiedBorder': '#3399cc',
							'tab.inactiveModifiedBorder': '#3399cc80',
							'tab.lastPinnedBorder': '#585858',
							'tab.unfocusedActiveBackground': '#2b303b',
							'tab.unfocusedActiveForeground': '#dfe1e880',
							'tab.unfocusedActiveModifiedBorder': '#3399cc80',
							'tab.unfocusedInactiveBackground': '#21252d',
							'tab.unfocusedInactiveForeground': '#6e7d8880',
							'tab.unfocusedInactiveModifiedBorder': '#3399cc40',
							'terminal.border': '#1a1d23',
							'terminal.dropBackground': '#343d466f',
							'terminal.selectionBackground': '#ffffff40',
							'testing.iconErrored': '#f14c4c',
							'testing.iconFailed': '#f14c4c',
							'testing.iconPassed': '#73c991',
							'testing.iconQueued': '#cca700',
							'testing.iconSkipped': '#848484',
							'testing.iconUnset': '#848484',
							'testing.message.error.decorationForeground': '#9b4d55',
							'testing.message.error.lineBackground': '#ff000033',
							'testing.message.hint.decorationForeground': '#eeeeeeb3',
							'testing.message.info.decorationForeground': '#518cc7',
							'testing.message.info.lineBackground': '#007fff33',
							'testing.message.warning.decorationForeground': '#ebcb8b',
							'testing.message.warning.lineBackground': '#ffd00033',
							'testing.peekBorder': '#9b4d55',
							'testing.runAction': '#73c991',
							'textBlockQuote.background': '#7f7f7f1a',
							'textBlockQuote.border': '#007acc80',
							'textCodeBlock.background': '#0a0a0a66',
							'textLink.activeForeground': '#3794ff',
							'textPreformat.foreground': '#d7ba7d',
							'textSeparator.foreground': '#ffffff2e',
							'titleBar.activeForeground': '#cccccc',
							'titleBar.inactiveForeground': '#cccccc99',
							'toolbar.activeBackground': '#63666750',
							'toolbar.hoverBackground': '#5a5d5e50',
							'tree.indentGuidesStroke': '#585858',
							'tree.tableColumnsBorder': '#cccccc20',
							'welcomePage.progress.background': '#252932',
							'welcomePage.progress.foreground': '#5c6bc0',
							'welcomePage.tileBackground': '#323843',
							'welcomePage.tileHoverBackground': '#3c4350',
							'welcomePage.tileShadow.': '#252932',
							'activityBar.activeBackground': null,
							'activityBar.activeFocusBorder': null,
							'button.border': null,
							contrastActiveBorder: null,
							contrastBorder: null,
							'debugToolBar.border': null,
							'diffEditor.border': null,
							'dropdown.listBackground': null,
							'editor.findMatchBorder': null,
							'editor.findMatchHighlightBorder': null,
							'editor.findRangeHighlightBorder': null,
							'editor.rangeHighlightBorder': null,
							'editor.selectionForeground': null,
							'editor.selectionHighlightBorder': null,
							'editor.snippetFinalTabstopHighlightBackground': null,
							'editor.snippetTabstopHighlightBorder': null,
							'editor.symbolHighlightBorder': null,
							'editor.wordHighlightBorder': null,
							'editor.wordHighlightStrongBorder': null,
							'editorCursor.background': null,
							'editorError.background': null,
							'editorError.border': null,
							'editorGhostText.border': null,
							'editorGroup.background': null,
							'editorGroup.emptyBackground': null,
							'editorGroup.focusedEmptyBorder': null,
							'editorGroupHeader.border': null,
							'editorGroupHeader.tabsBorder': null,
							'editorHint.border': null,
							'editorInfo.background': null,
							'editorInfo.border': null,
							'editorOverviewRuler.background': null,
							'editorUnnecessaryCode.border': null,
							'editorWarning.background': null,
							'editorWarning.border': null,
							'editorWidget.resizeBorder': null,
							'inputValidation.errorForeground': null,
							'inputValidation.infoForeground': null,
							'inputValidation.warningForeground': null,
							'list.filterMatchBorder': null,
							'list.focusForeground': null,
							'list.hoverForeground': null,
							'list.inactiveFocusBackground': null,
							'list.inactiveFocusOutline': null,
							'list.inactiveSelectionForeground': null,
							'menu.border': null,
							'menu.selectionBorder': null,
							'menubar.selectionBorder': null,
							'merge.border': null,
							'minimap.background': null,
							'notebook.cellEditorBackground': null,
							'notebook.cellHoverBackground': null,
							'notebook.focusedCellBackground': null,
							'notebook.inactiveSelectedCellBorder': null,
							'panelInput.border': null,
							'panelSectionHeader.border': null,
							'panelSectionHeader.foreground': null,
							'peekViewEditor.matchHighlightBorder': null,
							'quickInput.list.focusBackground': null,
							'searchEditor.findMatchBorder': null,
							'selection.background': null,
							'sideBar.border': null,
							'sideBar.foreground': null,
							'sideBarSectionHeader.border': null,
							'sideBarSectionHeader.foreground': null,
							'statusBar.border': null,
							'statusBar.debuggingBorder': null,
							'statusBar.noFolderBorder': null,
							'tab.activeBorder': null,
							'tab.activeBorderTop': null,
							'tab.hoverBorder': null,
							'tab.hoverForeground': null,
							'tab.unfocusedActiveBorder': null,
							'tab.unfocusedActiveBorderTop': null,
							'tab.unfocusedHoverBorder': null,
							'tab.unfocusedHoverForeground': null,
							'testing.message.hint.lineBackground': null,
							'titleBar.border': null,
							'toolbar.hoverOutline': null,
							'walkThrough.embeddedEditorBackground': null,
							'welcomePage.background': null,
							'welcomePage.buttonBackground': null,
							'welcomePage.buttonHoverBackground': null,
							'window.activeBorder': null,
							'window.inactiveBorder': null,
						},
					})

					Monaco.editor.setTheme('custom-theme')
				},
				{immediate: true, deep: true}
			)

			editor.onDidChangeModelContent(e => {
				const value = editor.getValue()
				if (props.modelValue !== value) {
					context.emit('update:modelValue', value, e)
				}
			})

			watch(
				() => props.modelValue,
				value => {
					if (editor.getValue() !== value) {
						editor.setValue(value)
					}
				}
			)
		})

		onUnmounted(() => {
			editor && editor.dispose()
		})
	},
})
</script>

<style lang="stylus">
.MonacoEditor
	width 100%
	height 20em
</style>
