export {default as MalInputAngle} from './MalInputAngle.vue'
export {default as MalInputColor} from './MalInputColor.vue'
export {default as MalInputNumber} from './MalInputNumber.vue'
export {default as MalInputVec2} from './MalInputVec2.vue'
export {default as MalExpButton} from './MalExpButton.vue'
