export {default as MalInputAngle} from './MalInputAngle.vue'
export {default as MalInputColor} from './MalInputColor.vue'
export {default as MalInputNumber} from './MalInputNumber.vue'
export {default as MalInputVec2} from './MalInputVec2.vue'
export {default as MalInputRect2d} from './MalInputRect2d.vue'
export {default as MalInputMat2d} from './MalInputMat2d.vue'
export {default as MalExpButton} from './MalExpButton.vue'
